spring:
  thymeleaf:
    cache: false
server:
  port: 8887
github:
  client_id: Iv1.c05ceb7c8c20ee6b
  client_secret: 03e0f140c2aaa315311655d712ac8e4cdb6a87ce
  redirect_uri: http://localhost:8887/callback